# Generated by Django 2.1.7 on 2019-02-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190213_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elit arcu, lobortis vitae convallis ve...', max_length=100),
            preserve_default=False,
        ),
    ]
