# Generated by Django 2.1.7 on 2019-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_blogpost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(max_length=150),
        ),
    ]
