# Generated by Django 3.0.3 on 2020-02-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200215_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='will-auto-update', unique=True),
        ),
    ]
