# Generated by Django 2.1.7 on 2019-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190214_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elit arcu, lobortis vitae convallis ve...', max_length=150),
            preserve_default=False,
        ),
    ]
