# Generated by Django 2.1.7 on 2019-02-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pictures',
            new_name='profile_picture',
        ),
    ]
