# Generated by Django 2.2.8 on 2020-01-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200122_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/user.svg', upload_to='profile_pictures/'),
        ),
    ]
