# Generated by Django 3.0.3 on 2020-04-22 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_full', models.ImageField(upload_to='photos')),
                ('front_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
