# Generated by Django 3.0.3 on 2020-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='sub_title',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
