# Generated by Django 3.0.3 on 2020-04-24 13:25

from django.db import migrations
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200423_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
    ]
