# Generated by Django 3.0.3 on 2020-04-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_photo_exif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='images/albums')),
            ],
            options={
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='background',
            field=models.ImageField(upload_to='images/sites'),
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Album'),
        ),
    ]
