# Generated by Django 3.0.3 on 2020-04-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200425_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='sub_title',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
