# Generated by Django 3.0.3 on 2020-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
