# Generated by Django 3.0.3 on 2020-05-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_frontpage_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='front_page',
            new_name='portfolio',
        ),
    ]
