# Generated by Django 3.0.3 on 2020-05-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200508_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='text_placement',
            field=models.CharField(choices=[('left', 'Left'), ('mid', 'Middle'), ('right', 'Right')], default='left', max_length=6),
        ),
    ]
