# Generated by Django 3.0.3 on 2020-05-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_frontpage_text_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='button_text',
            field=models.CharField(default='See more', max_length=25),
            preserve_default=False,
        ),
    ]
