# Generated by Django 3.0.3 on 2020-05-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_frontpage_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='frontpage',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='frontpage',
            name='text_placement',
        ),
        migrations.RemoveField(
            model_name='frontpage',
            name='title',
        ),
    ]
