# Generated by Django 3.0.3 on 2020-05-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200509_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frontpage',
        ),
    ]
