# Generated by Django 3.0.3 on 2020-05-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homepage',
            new_name='Frontpage',
        ),
    ]
