# Generated by Django 3.0.3 on 2020-05-13 08:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200509_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='background',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/sites'),
        ),
    ]
