# Generated by Django 3.0.3 on 2020-05-13 08:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20200513_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/albums'),
        ),
    ]
