# Generated by Django 3.0.7 on 2020-07-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20200513_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
