# Generated by Django 3.0.7 on 2020-07-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20200701_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='photo1',
        ),
    ]
