# Generated by Django 3.0.7 on 2020-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_remove_site_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='photo1',
            field=models.ImageField(null=True, upload_to='images/sites'),
        ),
    ]
