# Generated by Django 3.0.7 on 2020-07-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_site_photo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='images/sites'),
        ),
        migrations.AlterField(
            model_name='site',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/sites'),
        ),
    ]
