# Generated by Django 3.0.7 on 2020-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20200702_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontpage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
