# Generated by Django 3.0.7 on 2020-07-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20200702_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='portfolio',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Photo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
