# Generated by Django 3.0.7 on 2020-07-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_auto_20200702_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='frontpage_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='portfolio_bool',
            field=models.BooleanField(default=False),
        ),
    ]
