# Generated by Django 3.0.7 on 2020-07-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_auto_20200702_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Photo'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Photo'),
        ),
    ]
