# Generated by Django 3.0.7 on 2020-07-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_auto_20200709_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='frontpage',
            name='photo_full',
            field=models.ImageField(null=True, upload_to='frontpage'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo_full',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
    ]
