# Generated by Django 3.0.7 on 2020-07-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_auto_20200702_1813'),
        ('portfolio', '0034_auto_20200709_1623'),
    ]

    operations = [
    ]
