# Generated by Django 3.0.7 on 2020-07-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_merge_20200710_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.AlterField(
            model_name='frontpage',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Photo'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Photo'),
        ),
    ]
