# Generated by Django 3.0.7 on 2020-07-20 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_auto_20200710_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
