# Generated by Django 3.0.7 on 2020-07-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_album_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
